#SPDX-License-Identifier: GPL-3.0-only
---
# handlers file for ansible-royco-ntp
- name: Restart chrony
  become: true
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: Restart gpsd
  become: true
  ansible.builtin.service:
    name: gpsd
    state: restarted

- name: Restart system
  become: true
  ansible.builtin.reboot:
    msg: "Rebooting machine with Ansible"